AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  FeedMyTripApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Feed My Trip API
      StageName: Beta

  TripsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: fmt-lambda-trips
      Runtime: go1.x
      CodeUri: ./deploy/trips.zip
      Policies: AmazonDynamoDBFullAccess
      Tracing: Active
      Events:
        GetTrips:
          Type: Api
          Properties:
            RestApiId: !Ref FeedMyTripApiGateway
            Path: /trips
            Method: get
        PostTrips:
          Type: Api
          Properties:
            RestApiId: !Ref FeedMyTripApiGateway
            Path: /trips
            Method: post
        PatchTrip:
          Type: Api
          Properties:
            RestApiId: !Ref FeedMyTripApiGateway
            Path: /trips/{id}
            Method: patch
        DeleteTrip:
          Type: Api
          Properties:
            RestApiId: !Ref FeedMyTripApiGateway
            Path: /trips/{id}
            Method: delete
        PostParticipant:
          Type: Api
          Properties:
            RestApiId: !Ref FeedMyTripApiGateway
            Path: /trips/{id}/participants
            Method: post
        PatchParticipant:
          Type: Api
          Properties:
            RestApiId: !Ref FeedMyTripApiGateway
            Path: /trips/{id}/participants/{participantId}
            Method: patch
        DeleteParticipant:
          Type: Api
          Properties:
            RestApiId: !Ref FeedMyTripApiGateway
            Path: /trips/{id}/participants/{participantId}
            Method: delete
        PostInvite:
          Type: Api
          Properties:
            RestApiId: !Ref FeedMyTripApiGateway
            Path: /trips/{id}/invites
            Method: post
        DeleteInvite:
          Type: Api
          Properties:
            RestApiId: !Ref FeedMyTripApiGateway
            Path: /trips/{id}/invites/{inviteId}
            Method: delete
        PostItinerary:
          Type: Api
          Properties:
            RestApiId: !Ref FeedMyTripApiGateway
            Path: /trips/{id}/itineraries
            Method: post
        PatchItinerary:
          Type: Api
          Properties:
            RestApiId: !Ref FeedMyTripApiGateway
            Path: /trips/{id}/itineraries/{itineraryId}
            Method: patch
        DeleteItinerary:
          Type: Api
          Properties:
            RestApiId: !Ref FeedMyTripApiGateway
            Path: /trips/{id}/itineraries/{itineraryId}
            Method: delete
